### ISSUE TITLE
[1.4] Issues with the "fatal unloading error" screen

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1591] opened 2021-06-25 20:12 UTC
### Description
1. Pressing "Exit" hangs.
2. Pressing "Open Logs" rapidly changes resolutions, plays a sound, and spams the log with the message posted below.

### Log file
1. No logs
2. 
```
[22:13:20] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "C:\Users\USER\Documents\My Games\Terraria\ModLoader\Beta\Logs\client.log" 
[22:13:20] [Main Thread/ERROR] [Terraria]: System.ComponentModel.Win32Exception (32): The process cannot access the file as it is being used by another process. (this part is translated)
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Terraria.ModLoader.Core.LoggingHooks.<>c.<HookProcessStart>b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Core\LoggingHooks.cs:line 21
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Terraria.ModLoader.UI.UIErrorMessage.OpenFile(UIMouseEvent evt, UIElement listeningElement) in tModLoader\Terraria\ModLoader\UI\UIErrorMessage.cs:line 138
   at Terraria.UI.UIElement.Click(UIMouseEvent evt) in tModLoader\Terraria\UI\UIElement.cs:line 377
   at Terraria.UI.UserInterface.Update(GameTime time) in tModLoader\Terraria\UI\UserInterface.cs:line 140
   at Terraria.Main.UpdateUIStates(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 13046
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12710
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12482
```

### Steps to reproduce
This can be reproduced if you have latest version of [Cheatsheet for 1.4](https://github.com/direwolf420/CheatSheet/releases), and any 1.4 mod that is either 1. not updated to work on latest 1.4 tml, or 2. with use of an older 1.4 tml version  that had issues on load.

### Expected behavior 
Exit the game, or open logs

### Actual behavior
Hangs

### Reproduction frequency
100%

### Additional Information
Screenshot of the debugger attached
![hang](https://user-images.githubusercontent.com/15894498/123480235-550b1380-d602-11eb-9061-4fe6ff9c4d7e.png)

**Comment by Solxanich** [comment] 2021-06-29 01:58
Linking #1561 as possible duplicate of the log portion mentioned in this issue.

**Closed** 2021-07-27 17:42 UTC
