### ISSUE TITLE
tModLoader Family Sharing issues

### ISSUE THREAD

**Issue by Splinkarooni** [tModLoader/tModLoader#1014] opened 2020-07-15 16:01 UTC
I bought the game on my dad's account since I didn't have one already, I created my account and family shared the games on my dad's account. it's unfair I have to pay for something again after buying it already on another account, any help would be greatly appreciated :)

(sorry if I sound like a Karen, and or sorry if my grammar is bad)

**Comment by Mirsario** [comment] 2020-07-15 16:32
Duplicate of #881. You can just [install tML manually](https://github.com/tModLoader/tModLoader/releases), or look for other workarounds in that issue's thread. The issue seems to be up to Valve to solve.

**Closed by Mirsario** 2020-07-15 16:32 UTC
