### ISSUE TITLE
tModLoader not enabled for family share accounts on steam?

### ISSUE THREAD

**Issue by dozzzz02** [tModLoader/tModLoader#881] opened 2020-05-16 17:56 UTC
Edit by developer:
___
# We are aware of family sharing issues but it may take some time to solve it. For now try logging into the parent account to see if it works there.

Does the TML team not want this? The game itself is already family shared.

**Comment by Jofairden** [comment] 2020-05-16 18:49
No idea yet, but will look into it.

**Comment by MeDerpWasTaken** [comment] 2020-05-16 20:35
That seems like a steam issue probably, but I don't know

**Comment by Jofairden** [comment] 2020-05-17 14:35
I dont know how to enable it, if anyone can find  a steamworks setting let me know (afaik, this should work fine as long as you have it enabled on your account)

**Comment by KiltedSquirrel** [comment] 2020-05-17 22:42
I am by no means knowledgeable but if the dozzzz02 is seeing the same thing I am.  Try to run tmodloader.exe and it opens up Steam and goes to the install page for TModLoader.  I am wondering if it doesn't have something to do with the call to see if the user owns Terraria or not.

I found the following: https://partner.steamgames.com/doc/webapi/ISteamUser

It looks like there is a check to verify if the Steam User owns the game or not.

**Comment by FforSteam** [comment] 2020-05-18 11:25
Does that mean i need to buy the game now to play tmodloader ? :(

**Comment by Jofairden** [comment] 2020-05-18 17:05
Of course you need to buy the game, we dont condone piracy. Terraria is only $10, come on man...

**Comment by dozzzz02** [comment] 2020-05-19 07:28
> Of course you need to buy the game, we dont condone piracy. Terraria is only $10, come on man...

Obvious issues with this statement assigned, -- for some -- having family share is equal to having the game. They may have multiple accounts they bought games and wish to play one on the other.

**Comment by Jofairden** [comment] 2020-05-19 07:55
> 
> 
> > Of course you need to buy the game, we dont condone piracy. Terraria is only $10, come on man...
> 
> Obvious issues with this statement aside, -- for some -- having family share is equal to having the game. They may have multiple accounts they bought games on and wish to play one on the other.

I agree, and there is nothing wrong with family sharing I dont think, but we have no options for it ourselves so I really dont know if we can add support for it. Whatever issue you have with the statement doesn't matter, it's silly enough that people aren't willing to buy the game.

**Comment by MeDerpWasTaken** [comment] 2020-05-19 12:42
Family Share works with mods

**Comment by KiltedSquirrel** [comment] 2020-05-19 15:31
Darn shame.  TModLoader worked fine with Family Sharing before it was added to Steam.  But it sounds like we'll have to pay for another copy of Terraria if we want to use it on additional family accounts.

**Comment by MeDerpWasTaken** [comment] 2020-05-19 22:37
Strange

**Comment by Jofairden** [comment] 2020-05-20 08:20
We are still looking into this, apparently logging into the owner account and "buying" TML works or something, but yeah it's supposed to work.

**Comment by pino4pino** [comment] 2020-05-21 14:36
So claiming the mod through the store on the account that owns it does work and will have it appear in your library. But when you try to launch it still sends you back to the store to the tmodloader mod page.

**Comment by Jofairden** [comment] 2020-05-21 17:36
Can you just try a manual installation for now?
Just uninstall (if even applicable) tML on steam, grab the .zip from github and just put the files somewhere.

**Comment by dozzzz02** [comment] 2020-05-21 19:40
> and I still can't believe people are willing to defend piracy.

I reasonably can. 

I guess the topic is closed, I'll do it manually for now.

**Comment by Jofairden** [comment] 2020-05-22 08:12
Actually I wanted to keep this one open, I've been redirecting numerous others to this one.

**Comment by MegaCringe** [comment] 2020-05-27 20:31
So i switched to the account that is sharing Terraria to download tModLoader, then switched back to my main account, Now whenever i press play it just brings me to the store page for tModLoader.

**Comment by Jofairden** [comment] 2020-05-28 11:23
Thanks for the recording, I'm going to forward this to Valve once again.

**Comment by Ethorbit** [comment] 2020-06-23 03:38
Any progress?

**Comment by Jofairden** [comment] 2020-06-24 09:33
Unfortunately not, I haven't had any response from Valve sadly.
I think the issue is that TML is implemented oddly on the technical side at Valve, since we are considered a DLC but still a separate game in the store and library. I think the issue with family sharing arises from this fact.

**Comment by julioandre14** [comment] 2020-06-24 15:03
i think i resolved this problem, if you download your tmodloader via the primary account, you can enter the folder and execute tModLoader and finally, play the game without any issues
![2020-06-24](https://user-images.githubusercontent.com/67379845/85580975-942f0f00-b612-11ea-819f-b336176bbb7b.png)
(sorry for my poor english, im brazilian, also is my first time in github)

**Comment by Jofairden** [comment] 2020-06-26 08:35
Yes it works via the primary account, but not the associated accounts which is the issue.

**Comment by VoxX297** [comment] 2020-07-05 02:51
Look at the manual installation :)

https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players

**Comment by PandaJabba** [comment] 2020-08-03 07:55
Any news on if this is fixed yet?

**Comment by Ethorbit** [comment] 2020-08-12 22:35
This is more of a workaround than a ~~solution~~ as you will have to launch the TModLoader.exe manually (Steam will try to luanch Terraria.exe and cause crashes), but to launch TModLoader on a family shared account you can download the files manually [here](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation)

Then just drag & drop the rar contents into your Terraria's installation directory.

### Done!
Now launch TModLoader.exe. Steam will still show you as playing Terraria as if you had downloaded it on Steam.

**Comment by smokemeowt** [comment] 2020-08-31 23:30
> This is more of a workaround than a ~solution~ as you will have to launch the TModLoader.exe manually (Steam will try to luanch Terraria.exe and cause crashes), but **to launch TModLoader on a family shared account** you can download the files manually [here](https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation)
> 
> Then just drag & drop the rar contents into your Terraria's installation directory.
> 
> ### Done!
> Now launch TModLoader.exe. Steam will still show you as playing Terraria to friends.

I want to point out an issue of doing it like this though. I have friends who run tmodloader through steam, and I manually installed it exactly word for word as it says to on the tmodloader github. I can't join friends who are running the actual steam tmodloader.

**Comment by Just-a-Unity-Dev** [comment] 2022-01-15 11:55
any fix yet?

**Comment by bripendo** [comment] 2022-03-20 10:56
Another issue
Apparently Steam family shared Terraria doesn't work at all with newer TML updates
I tried to launch the manually installed tmodloader and it just displays this error:
![image](https://user-images.githubusercontent.com/101973497/159158964-f0be4fb8-9ba3-4b31-a575-9f9f670820e3.png)

**Comment by Riuyt2** [comment] 2022-05-12 09:01
if you dont have steam you need to instal that . I installed steam and it opened brawser mode

**Comment by DoomSlayer-cm** [comment] 2022-09-02 02:58
has this been fixed yet? I recently got Terraria via Family Share, and I can't get TModLoader.

**Comment by Chicken-Bones** [comment] 2022-09-02 07:18
You can now play tML but you won't be able to use any steam features. If you want to join friends via steam, or use steam overlay, you'll need to buy Terraria.

**Comment by DoomSlayer-cm** [comment] 2022-09-02 12:34
> You can now play tML but you won't be able to use any steam features. If you want to join friends via steam, or use steam overlay, you'll need to buy Terraria.

how do you do it though?

**Comment by DoomSlayer-cm** [comment] 2022-09-03 21:27
anyone know how to play tModLoader with family shared Terraria?

**Comment by DoomSlayer-cm** [comment] 2022-09-04 21:53
does anyone know of a way to run tModLoader with a family shared Terraria?

**Comment by Chicken-Bones** [comment] 2022-09-06 00:56
Just launch it. It works now.

**Comment by JavidPack** [comment] 2022-09-14 20:52
I'm still getting reports of the game failing to launch for gog users, I'll update this later with more logs.

**Comment by Solxanich** [comment] 2022-09-15 01:34
All, to be specific:
Version 2022.8 onwards of tmodloader should support family share while launched from an existing or manual install. 
In order to get a manual install, follow the steps here: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

As mentioned earlier, due to limitations in Steam, the following is not supported on a family share copy of tmodloader:
1) downloading tmodloader in steam client
2) 'Proper' Steam Overlay 
3) Using Steam to play with friends (Steam Multiplayer)

We recommend downloading tmodloader using the account that owns Terraria or following the manual install process mentioned earlier. 

Workshop content is delivered using the same solution our GoG users have; any items you subscribe to in Steam Client will not download.

**Comment by ziproot** [comment] 2022-10-05 02:01
The manual installation does not appear to work on Linux. It just says "Please ensure Steam is logged in and running," even when Steam is logged in and running.
EDIT: [log](https://github.com/tModLoader/tModLoader/files/9712000/client.log)
EDIT 2: Looks like I'm in the same boat as the GOG users except that I can't downgrade.

**Comment by ChickenChunk579** [comment] 2023-01-31 20:23
I am having the same issue, but I can’t even add tModLoader to my library.

**Comment by Solxanich** [comment] 2023-02-01 00:01
Hi All,

I think we have a working solution now? 

Follow the manual installation steps for GoG, just like 1.3, but when go to launch it, run start-tnodloader-FamilyShare. 

For manual installation instructions, see a couple posts ago

**Comment by bripendo** [comment] 2023-02-02 13:23
But as far as I see, the mod browser in 1.4 seems to be Seam workshop-dependent
When I click download it shows the process of downloading but when it's done, I don't have the mod downloaded and game wants me to go to Workshop and subscribe to mods manually

**Comment by bripendo** [comment] 2023-02-02 14:24
Edit: Found a workaround for installing mods too

When you install a mod through in-game mod browser, downloded mods will appear in 
[TModLoader's files folder location]\steamapps\workshop\content\1281930\\[presumably ID of mod on Steam Workshop]\\[Number that seems to resemble tMod's version]
Where 1281930 is TModLoader's appID on Steam

Each .tmod file will be in separate folder located in other folder, which is in TModoader's steamapps folder (images below)

![image](https://user-images.githubusercontent.com/101973497/216346898-46737d47-4538-4c2e-9891-1f690a5ae99f.png)
![image](https://user-images.githubusercontent.com/101973497/216348584-b1b7f5cc-7d6a-4df5-9890-cd439f33b339.png)
![image](https://user-images.githubusercontent.com/101973497/216348922-f8e2dc68-4ac9-4272-9045-212c1a69a12b.png)
![image](https://user-images.githubusercontent.com/101973497/216348930-2c45445f-d9c2-48d1-8419-21fad57fcbd8.png)


You can simply copy the .tmod file to Documents\My Games\Terraria\tModLoader\Mods

![image](https://user-images.githubusercontent.com/101973497/216349502-035a26fe-3c42-42e9-9205-1d2ac9a0cb6d.png)

When you close tModLoader and re-run start-tModLoader-FamilyShare
Game will automatically detect .tmod files in Mods folder and to enable them follow images below:
![image](https://user-images.githubusercontent.com/101973497/216350273-4429bcd8-dce0-44da-a5e3-b56109b84672.png)
![image](https://user-images.githubusercontent.com/101973497/216350330-3a12af1a-068b-4afc-9d94-c8d0d6682ffb.png)
![image](https://user-images.githubusercontent.com/101973497/216350447-72aa9c93-7610-4801-a774-64f91ebde200.png)
![image](https://user-images.githubusercontent.com/101973497/216350464-40a4f814-8f84-46ee-b378-b23f1b0bc24d.png)

When you click back, game will reload and selected mods will be ready to play!

**Comment by Solxanich** [comment] 2023-02-02 14:49
Thats weird. 
It should be autodetecting mods from that original location, as that is how GoG works. 
I'll take a look at code, thanks for reporting!

**Comment by Foxtrot-77** [comment] 2023-04-03 15:10
I have a suggestion, don't know how to do it tho. (I have no coding experience, just so you know) Tmodloader is listed as a mod for Terraria on Steam. This forces you to own Terraria to download TML. But if TML was a standalone "game" it would work by itself. Take Sven Co-op for example. It is a mod for HL1, but it is listed on Steam as its own thing. So, even though i have HL1 family shared, i can play Sven Co-op. I'm not sure how you would do it, but maybe change TML from a Terraria mod to its own item? That would work.

**Comment by bripendo** [comment] 2023-04-04 18:26
Actually
Yeah, but I have no idea about how are files accessed then
It might be good solution, or might be not, depending on how Steam works

**Comment by Solxanich** [comment] 2023-04-04 18:42
So, yes, we have asked Steam/Valve about that before. 
Short answer we were told no.
Long answer involves business politics, so wasn't going anywhere. 

Today, you can manually install tmodloader following the GoG instructions and that gets you a playable tmodloader. 
Just can't download it in Steam itself
(+/- some bugs that sometimes there)

**Closed** 2023-06-02 02:49 UTC
Labels: Bug, Needs Further Testing, Requestor-Player, Benefit - High, Complexity - Medium
