### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by LordTSI** [tModLoader/tModLoader#1193] opened 2020-11-11 02:25 UTC
### Description
<i have no sound but audio sliders are just [fine>](url)

### Log file
<client.log](https://github.com/tModLoader/tModLoader/files/5521340/client.log>

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by imabigboi** [comment] 2020-11-11 12:45
yeah i have the same problem

**Comment by imabigboi** [comment] 2020-11-11 14:05
look at my issue (the one below yours) you will find some info

**Comment by mcnoobyson** [comment] 2020-11-11 14:52
The issue was caused by updating your vanilla terraria version to 1.4.1 (the newest update). As of right now, tmodloader only supports up to version 1.4, so you might have to wait some time before this issue is solved.

One solution might be to downgrade your Terraria version back to version 1.4, which i am working on right now. Will update if it works

**Comment by Mirsario** [comment] 2020-11-11 22:05
Duplicate of #1190. Will be fixed very soon.
(Why did you make 3 of these?)

**Closed by Mirsario** 2020-11-11 22:05 UTC
