### ISSUE TITLE
Tmodloader No Sound.

### ISSUE THREAD

**Issue by DauidBeck** [tModLoader/tModLoader#1194] opened 2020-11-11 16:59 UTC
Booted up tmodloader today, No sound, volume sliders are at 100%, tried booting up terraria and it had sound. 
Conclusion: Tmodloader isn't giving off sound

**Comment by Albhis** [comment] 2020-11-11 18:20
Having the same issue, same things. Even when loading without any mods active no sound is made.

**Comment by bababooey-source** [comment] 2020-11-11 19:32
I'm having the same problem, everything I try doesn't help, I checked the wavebank, updated sound drivers, restarted, reinstalled, verified both tmodloader app and terraria, and restarted my computer entirely, nothing worked

**Comment by Mirsario** [comment] 2020-11-11 22:04
Duplicate of #1190. Will be fixed very soon.

**Closed by Mirsario** 2020-11-11 22:04 UTC

**Comment by kinemoon** [comment] 2020-11-11 23:57
Всё фикс вышел 11 8, всё работает.

**Comment by bababooey-source** [comment] 2020-11-12 01:44
Thank you! Take your time please
