### ISSUE TITLE
Add tModLoader to Nvidia GeForce NOW

### ISSUE THREAD

**Issue by Yokoharu** [tModLoader/tModLoader#1287] opened 2021-01-15 12:18 UTC
### Description
Contact NVIDIA to opt-in into their GeForce NOW app.

### What does this proposal attempt to solve or improve?
This will mean that people that have GeForce NOW could play Terraria modded too. It would also mean that people that previously had too weak of machines to handle more resource consuming mods could finally try them out. Since the policy change, developers can message NVIDIA to opt-in into their service. Since the tModLoader is already on Steam I'd assume that the process of adding it to the app would be easy.

**Comment by Chicken-Bones** [comment] 2021-01-16 09:04
Duplicate of https://github.com/tModLoader/tModLoader/issues/1094

**Closed by Chicken-Bones** 2021-01-16 09:04 UTC
