### ISSUE TITLE
[1.4-Alpha] Character Creator Color Code Copy and Paste Crashes the game.

### ISSUE THREAD

**Issue by JVGA8837** [tModLoader/tModLoader#1710] opened 2021-08-07 19:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Just found it out and when ever you copy a color code to the clipboard and try to paste it, it crashes. Not that big of a deal, but just pointing it out.

**Comment by JavidPack** [comment] 2021-08-07 19:12
Thanks. This is a duplicate of #1649 , so we'll be tracking this there.

**Closed by JavidPack** 2021-08-07 19:12 UTC
