### ISSUE TITLE
tModLoader Server Not Working

### ISSUE THREAD

**Issue by Underplayer97** [tModLoader/tModLoader#1784] opened 2021-08-24 02:22 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

Hello,
I have searched wide in the internet and tried so many things but it still does not work, I am currently having issues with trying to setup a tModLoader Server. I am currently using linux and use the operating system of raspbian arm64 (also tried normal version), I have also used Ubuntu 21.04 x64, though I always get this error: ./tModLoaderServer: line 48: ./tModLoaderServer.bin.x86: cannot execute binary file: Exec format error . Here is what my steps that I set it up:
1. Download tModLoader.zip (also have tried tar.gz)
2. unzip file
3. do command chmod u+x tModLoaderServer* (If i dont do the * at the end it gives me a permission error)
4. start ./tModLoaderServer

I have also used mono and ran but still gave error (log will be posted)
[server.log](https://github.com/tModLoader/tModLoader/files/7035979/server.log) <- This file is when I do mono tModLoaderServer.exe

The device I use is a raspberry pi 4b, I am hoping to find a way to make this work so that I can make modded servers to play with my friends.

Note: TShock Terraria does work but have not tried normal terraria server.

### Steps to reproduce

1. Download raspbian arm64
2. Flash mini SD card with raspbian
3. Add to raspberry pi 4b
4. Setup raspbian 
5. Download tModLoader-Linux.zip/tar.gz
6. Add tModLoader zip or tar.gz file
7. Unzip file
8. Open file
9. Activate chmod u+x tModLoaderServer*
10. Do ./tModLoaderServer

If trying to get mono error replace step 10 with this:
10. Do mono tModLoaderServer.exe

### Expected Behavior

It should load up tModLoader and let me add mods and run the server.

### Actual Behavior

It keeps crashing and giving exec format error

### Reproduction frequency

The error works every time

**Comment by JavidPack** [comment] 2021-08-24 04:21
Your only option that has any likelyhood of working is the mono approach, since the pi is an ARM processor, but not by running `mono` directly, you should be running the mono version of `./tModLoaderServer`. To do this, run `cp tModLoader-mono tModLoaderServer`, this should replace the regular server script with the mono version. That script does some things necessary for it to load. 

That said, I still haven't confirmed with anyone that running a tmod server on a pi works. People have come and gone from the discord chat attempting the same thing.

**Comment by Underplayer97** [comment] 2021-08-24 20:53
I got it somewhat working, it did start up and started running but when I add mods into it, it breaks in the startup. It only happens to big mods like calamity, other smaller mods like magic storage works. I looked around and found it might be a RAM issue, but I have 8GB of ram and I was wondering is there any way to fix the RAM issue.

**Comment by Underplayer97** [comment] 2021-08-28 00:47
Hey I was wondering if there is any way to fix this, I would like to setup a server with big mods but any big mod that I try keeps crashing the server. I hope that there is a fix for this.

**Comment by Steviegt6** [comment] 2021-08-30 15:58
> Hey I was wondering if there is any way to fix this, I would like to setup a server with big mods but any big mod that I try keeps crashing the server. I hope that there is a fix for this.

Given the mods you're using, this doesn't sound like an issue with insufficient RAM. If it is, though, tModLoader 64bit has recently started distributing Linux server builds: https://github.com/Dradonhunter11/tModLoader64bit/releases/download/0.11.8.5/tModLoader64Bit-Linux-Server.zip (https://github.com/Dradonhunter11/tModLoader64bit/releases).

**Comment by Underplayer97** [comment] 2021-08-30 16:19
Yeah I found out that it wasn't RAM, I'm not sure what is breaking the server. I had to reflash my sdcard to Ubuntu and it now works

**Comment by Steviegt6** [comment] 2021-08-30 18:50
> Yeah I found out that it wasn't RAM, I'm not sure what is breaking the server. I had to reflash my sdcard to Ubuntu and it now works

Should probably close this issue, then. 👍

**Closed** 2021-08-30 19:55 UTC

**Comment by ASterle** [comment] 2021-09-08 22:52
I had the same issue (probably)

```
An error occurred while loading 
The mod responsible is unknown and tModLoader must be restarted.

System.NullReferenceException: Object reference not set to an instance of an object.
  at System.Collections.Generic.LargeArrayBuilder[T].GetBuffer (Int32 index) [0x00022] in System.Core.dll
  at System.Collections.Generic.LargeArrayBuilder[T].CopyTo (CopyPosition position, T[] array, Int32 arrayIndex, Int32 count) [0x00041] in System.Core.dll
  at System.Collections.Generic.SparseArrayBuilder[T].CopyTo (T[] array, Int32 arrayIndex, Int32 count) [0x0009a] in System.Core.dll
  at System.Collections.Generic.SparseArrayBuilder[T].ToArray () [0x00028] in System.Core.dll       
  at System.Linq.Enumerable+Concat2Iterator[TSource].ToArray () [0x00024] in System.Core.dll        
  at System.Linq.Enumerable.ToArray[TSource] (IEnumerable[T] source) [0x00021] in System.Core.dll   
  at Terraria.ModLoader.ItemLoader.ResizeArrays (Boolean unloading) [0x00372] in tModLoader64BitServer.exe
  at Terraria.ModLoader.ModContent.ResizeArrays (Boolean unloading) [0x00000] in tModLoader64BitServer.exe
  at Terraria.ModLoader.ModContent.Load (CancellationToken token) [0x00050] in tModLoader64BitServer.exe
  at Terraria.ModLoader.ModLoader.Load (CancellationToken token) [0x00098] in tModLoader64BitServer.exe
```

The error above is from the 64 bit version linked above, 32 bit has the same error after using tModLoader-mono.

I fixed it by going to https://www.mono-project.com/download/stable/#download-lin-debian and downloading the latest version of mono from there (Going from version 5.18.0.240 to 6.12.0.122)

Since it worked on Ubuntu I guess the version in their repos is newer than the one in Debians.
