### ISSUE TITLE
Crash on character creation menu

### ISSUE THREAD

**Issue by mcwilliamsjh** [tModLoader/tModLoader#1711] opened 2021-08-07 19:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When making a new character the copying from clipboard then pasting from clip board crashes the game.

### Steps to reproduce

1. create new character
2. click "copy from clipboard"
3. click "paste from clipboard"

### Reproduction frequency

Consistent

**Comment by JavidPack** [comment] 2021-08-07 19:32
Duplicate of #1649 , we'll track this over there.

**Closed by JavidPack** 2021-08-07 19:32 UTC
