### ISSUE TITLE
TMod Loader isn't installing

### ISSUE THREAD

**Issue by CloudyDoggo** [tModLoader/tModLoader#1151] opened 2020-10-18 08:45 UTC
When I try to install TMod loader on steam it just refreshes the page and no downloads take place.

I have family sharing with one other account on and have checked the steam page, much to my dismay a few other people had the same problem but did not specify whether they were family sharing or not. (I'm on windows and have no clue how to even access the terraria files, so additional guidance may be needed.)
 The other account has granted access to terraria already.

**Comment by JavidPack** [comment] 2020-10-18 09:10
Duplicate of #881 . For now the instructions for family shared terraria is to do the manual instructions posted here: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

**Closed by JavidPack** 2020-10-18 09:10 UTC
