### ISSUE TITLE
Tmodloader for mobile

### ISSUE THREAD

**Issue by gio54man87** [tModLoader/tModLoader#1310] opened 2021-01-29 20:27 UTC
i think you guys should make a mobile version of tml 

### What does this proposal attempt to solve or improve?
it gives mobile players the option to apply mods for terraria on there devices and it makes the game more fun for mobile players 

### Which (other) solutions should be considered?
just by adding tmodloader to google play store and the ios app store please thanks so much and big support here

**Comment by Pacnysam** [comment] 2021-01-29 20:47
> i think you guys should make a mobile version of tml
> 
> ### What does this proposal attempt to solve or improve?
> it gives mobile players the option to apply mods for terraria on there devices and it makes the game more fun for mobile players
> 
> ### Which (other) solutions should be considered?
> just by adding tmodloader to google play store and the ios app store please thanks so much and big support here

Porting something as large as tmodloader to mobile is no small feat, its just not as easy as "just adding tmodloader to google play store and the ios app store" and could take months or years even to do so. Considering many many factors, it would likely not make up for all of the blood, sweat and tears to port it over to mobile. Things such as device performance, small audience size, completely different codebase, etc, all come into play.

**Comment by Chicken-Bones** [comment] 2021-01-30 01:29
Duplicate of #677

**Closed by Chicken-Bones** 2021-01-30 01:29 UTC
