### ISSUE TITLE
Cannot Download Mods From Mod Browser on Linux Client

### ISSUE THREAD

**Issue by micahsoftdotexe** [tModLoader/tModLoader#1751] opened 2021-08-16 23:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

When I go to download a mod (I have tried several mods) in the mod browser, I click on the download button and the downloading status bar appears for a second and disappears immediately afterwards. According to the log file this seems to be an authentication issue. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6995886/client.log)

### Steps to reproduce

1. When on the title screen click on the Mod Browser button
2. From there click on the download button for a mod

### Expected Behavior

I expect for it to download a mod

### Actual Behavior

The download progression screen pops up for a second and then disappears and the mod is not downloaded. 

### Reproduction frequency

Every time

**Comment by Rijam** [comment] 2021-08-17 02:16
I know this doesn't solve your problem of downloading mods from the in game mod browser, but in the meantime you can manually download mods from the mirror: https://mirror.sgkoi.dev/

**Comment by Steviegt6** [comment] 2021-08-17 02:22
This is a known issue caused by Mono.

**Comment by Solxanich** [comment] 2021-08-17 13:48
Duplicate of https://github.com/tModLoader/tModLoader/issues/921
Unix mod downloads don't work.
Use the mirror given in https://github.com/tModLoader/tModLoader/issues/1751#issuecomment-899941588

**Closed** 2021-08-18 01:34 UTC
