### ISSUE TITLE
Game crashes at end of settling water step when entering a world with terraria set to high monitor resolution (i.e. 3840x1600p)

### ISSUE THREAD

**Issue by Ph-enix** [tModLoader/tModLoader#1661] opened 2021-08-01 20:52 UTC
### Description

When I try to enter into a world that has already been generated at a higher resolution (the resolution of my monitor is 3840x1600p), the game crashes to desktop at the end of the 'settling water' step.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/6913392/client.log)

### Steps to reproduce

1. Set Terraria resolution to a large resolution (I am at 3840x1600p using the in-game video settings, I saw another report for 5120x1440p). Windowed or Fullscreen.
2. Try to enter into a world with any character.

### Expected behavior 

The world should load and the game can be played at the resolution of the monitor.

### Actual behavior
Game closes and will shutdown at the 'Settling water 99%/100%' step.

### Reproduction frequency
Every time I try to enter a world at the resolution of my monitor.

### Additional Information
The crash happens consistently at the resolution of my monitor when full screen or windowed. If I switch to windowed using the game settings and go to a lower resolution (i.e. the default one) the world can be loaded into and the game played as expected.

Edit: Changing the tmodloader setting "Remove Forced Minimum Zoom" to 'Yes' instead of 'No' fixes this crash and the world loads as expected at any resolution fullscreen or windowed.

**Comment by coleboggus** [comment] 2021-08-02 05:23
Does this still occur if you disable minimum zoom under tmodloader settings? I was having a similar issue and this resolved it for me.

**Comment by Ph-enix** [comment] 2021-08-02 13:08
> 
> 
> Does this still occur if you disable minimum zoom under tmodloader settings? I was having a similar issue and this resolved it for me.

That's a good call - when I toggle that setting "Remove Forced Minimum Zoom" under the tmodloader settings to 'Yes' instead of the default 'No' then the world does load as expected. The GUI will initially be tiny, but using the in game slider you can increase the scale manually again and it'll look as intended. 

Thank you.

**Comment by freezebladeJD** [comment] 2021-08-05 05:19
I'm having the same issue when running 4k, except when I load up a world, it finishes loading completely but upon entering the world it crashes. I've tried full screen, windowed, and borderless but nothing affects it.

**Comment by Solxanich** [comment] 2021-08-14 17:50
[client (1).log](https://github.com/tModLoader/tModLoader/files/6986953/client.1.log)
Just tossing up another log here from someone else with different GPU manufacturer. 

On a different, on my QHD display, can't reproduce this. Given that, I'm presuming this is somehow related to a first time initialization of the minimum zoom variable being wrong. Given World Zoom is related to monitor size extensively, I would presume that it is initialized at under 100% by this Forced Minimum Zoom, and thus lighting tries to access an array thats sized by the monitor resolution itself. 
Haven't found the exact code however to fix it, but figured I'd leave a note since Contributions Welcome.

**Comment by Solxanich** [comment] 2021-08-24 15:58
Stumbled across that vanilla forcefully corrects the "zoom" to be 1080p equivalent window size:
![image](https://user-images.githubusercontent.com/59670736/130649543-a160a5da-f1eb-4684-9331-65fb195480ee.png)

133% for a QHD monitor; ie 1440p * 3/4 => 1080p actual rendered. 
This tomfoolery doesn't happen on tMod.
![image](https://user-images.githubusercontent.com/59670736/130649934-58102e26-8a53-44cd-ae4e-6dbc8fd2b9df.png)

Coincidence? I have no idea

**Comment by Mirsario** [comment] 2021-09-07 16:51
Should be fixed with #1801

**Closed by Mirsario** 2021-09-07 16:51 UTC
Labels: Bug, Contributions Welcome/Easy
