### ISSUE TITLE
The 4k Screen resolution would cause the carsh when you join the world

### ISSUE THREAD

**Issue by IreneClift** [tModLoader/tModLoader#1690] opened 2021-08-04 11:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

**Comment by IreneClift** [comment] 2021-08-04 11:52
I can't join the world when my Screen resolution>2k

**Comment by Mirsario** [comment] 2021-08-05 21:47
Duplicate of #1661

**Closed by Mirsario** 2021-08-05 21:47 UTC

**Comment by IreneClift** [comment] 2021-08-08 09:47
Sorry I don't Find it because I use wrong keyword to search
