### ISSUE TITLE
Add Workshop

### ISSUE THREAD

**Issue by eyihsil** [tModLoader/tModLoader#1443] opened 2021-04-11 04:54 UTC
### Description

Add Workshop
### What does this proposal attempt to solve or improve?

This will make it more convenient to find mods with categorization

**Comment by Mirsario** [comment] 2021-04-11 11:34
Duplicate of #1276

**Closed by Mirsario** 2021-04-11 11:34 UTC

**Comment by eyihsil** [comment] 2021-04-17 22:38
How can I delete this issue
