### ISSUE TITLE
Asset not found

### ISSUE THREAD

**Issue by ertila007** [tModLoader/tModLoader#1702] opened 2021-08-05 17:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Whereas i'm in ice biome, at subterran, I was excavating ice blocks and snow blocks at search of new ores for my progression, especially tier 3 and 4 pre-hardmode ones. I made an attack with an Enchanted Boomerang and an error message of asset not found was displayed. But my game didn't crash and I did some minutes of playthrough before effortly closing the game.

PS: Log files are in pt-br language, but the error mensage are in english.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6940528/client.log)

### Steps to reproduce

0. Create a world with celebration mk 10 AND drunk world together (with advanced seeds mod);
1. Craft the Enchanted Boomerang (I did that at another session playthorugh)
2. Go to Underground Ice biome;
3. Try to make an attack wirh an enchanted boomerang from top to bottom
4. Getting that bug.

### Expected Behavior

There is some pallete somewhere. Or some graphic process.

### Actual Behavior

Possible error causing by lack of sprite of world or projectile regarding by Enchanted Boomerang.

### Reproduction frequency

Once, 100%.

### Additional Information

My modpool:
 "MaxStackExtra",
  "AdvancedWorldGen",
  "TorchGodTweaks",
  "MagicStorage",
  "CheatExtensions",
  "HEROsMod",
  "DayCounter",
  "SummonersAssociation",
  "Antisocial",
  "OreExcavator",
  "WMITF",
  "StarQoL"

**Comment by JavidPack** [comment] 2021-08-05 19:37
This is a duplicate of #1691 , we hope to fix this soon. In the meantime, you can delete the files mentioned and then use steam to "verify game integrity" and they should come back with the correct capitalization. You can also just rename these files to the correct capitalization. If you do that, you shouldn't have any more issues

**Closed by JavidPack** 2021-08-05 19:37 UTC
