### ISSUE TITLE
Tossing/Using healing potions causes heal as well as dropping

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#976] opened 2020-06-07 12:46 UTC
### Description
... but not potion sickness
https://youtu.be/eBWyWklPaUQ

### Steps to reproduce

See video

**Comment by JavidPack** [comment] 2020-09-18 04:56
I confirmed that this is a bug in Terraria 1.3.5.3, but not Terraria 1.4. The issue is DropSelectedItem sets itemAnimation = 10, but then sets selectedItem back to oldSelectItem, effectively skipping the checks in ItemCheck and putting the player in a state of already using the item. It's fixed in 1.4, and the code is rewritten a lot, but I think I have a fix for now.

**Closed** 2020-09-18 04:56 UTC
