### ISSUE TITLE
[1.4] Block placement/removal issue in multiplayer

### ISSUE THREAD

**Issue by MegaCactus27** [tModLoader/tModLoader#1817] opened 2021-09-05 03:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When trying to place/remove blocks in multiplayer on the Tmod 1.4 alpha, if a player (A) is standing close enough to another player's (B) cursor to be able to place/remove a block at B's cursor location, they will place/remove the block at both A's and B's cursor location, instead of just A's

### Steps to reproduce

requires 2 players (A and B)
1. B places their cursor over the tile where they wish to place/remove a block
2. A moves to a location close enough to place/remove a block at B's cursor location
3. A moves their cursor to a location other than B's cursor location where they wish to place/remove a block
4. A attempts to place/remove a block
5. the block will be placed/removed at both A and B's cursor locations instead of just at A's cursor location

### Expected Behavior

The block should only be placed at A's cursor location

### Actual Behavior

The block is placed at both A and B's cursor locations

### Reproduction frequency

I was able to reproduce the issue fairly easily, it is easier to reproduce if A has a larger block placement/removal range

**Comment by Solxanich** [comment] 2021-09-05 17:15
Thanks for Reporting!
I'm wondering if this is possibly a duplicate of: https://github.com/tModLoader/tModLoader/issues/1745 ?

Feel free to correct me if I'm wrong.

**Comment by MunchyG** [comment] 2021-09-10 11:23
yer sounds the exact same as mine

**Comment by MegaCactus27** [comment] 2021-09-11 01:02
> Thanks for Reporting and providing such great detail!
> I'm wondering if this is possibly a duplicate of: #1745 ?
> 
> Feel free to correct me if I'm wrong.

I didn't notice this was reported before because the link to the bug reports in the discord only shows some reports. Thanks for letting me know this was posted before!

**Comment by Mirsario** [comment] 2021-12-28 21:22
Worked around with the above PR; A more permanent fix coming soon.

**Closed by Mirsario** 2021-12-28 21:22 UTC
