### ISSUE TITLE
Character is shaking while jumping!

### ISSUE THREAD

**Issue by AriesStar1337** [tModLoader/tModLoader#757] opened 2020-01-01 16:03 UTC
### Description
I just install tModloader v0.11.6.1 and saw that when you jump the character keep moving up/down while jump everytime. No mods were used.

### Steps to Reproduce
1. Install Terraria
2. Install tModloader v0.11.6.1
3. Jump!

### Expected behavior 
Jump normally without shaking up/down.

### Actual behavior
Character Move up/down about 1-2 pixel while almost reaching the top of the jump.

### Reproduction frequency
Always happen but the shaking up/down pattern seem to be random.

### Additional Information
Recorded GIF
https://gyazo.com/d7b48075583ecb6e6e502f8c67c199bf

**Comment by JavidPack** [comment] 2020-01-01 20:44
Thanks for the report

Duplicate of #603

**Closed by JavidPack** 2020-01-01 20:44 UTC
